version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  node-app:
    # deploy:
    #  replicas: 6
    #  restart_policy:
    #   condition: any
    build: .
    image: kiglet/docker-node-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
    restart: always
      
  
  mongo:
   image: mongo
   environment:
    -MONGO_INITDB_ROOT_USERNAME: 1223d
    -MONGO_INITDB_ROOT_PASSWORD: 1223d
   volumes: 
    - mongo-db:/data/db
   restart: always
      
  redis:
   image: redis

volumes:
 mongo-db:
